apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeip.fullname" . }}-cm
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
  namespace: kube-system
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "reserved"
  KUBEIP_NODEPOOL: "default-pool"
  KUBEIP_FORCEASSIGNMENT: "true"
  KUBEIP_ADDITIONALNODEPOOLS: ""
  KUBEIP_TICKER: "5"
  KUBEIP_ALLNODEPOOLS: "false"
