apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeip.fullname" . }}-cm
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
data:
  KUBEIP_LABELKEY:            "{{ .Values.kubeip.labelkey }}"
  KUBEIP_LABELVALUE:          "{{ required "GKE cluster name needed ( .Values.kubeip.labelvalue  ) ! " .Values.kubeip.labelvalue }}"
  KUBEIP_NODEPOOL:            "{{ required "Targeted nodepool name needed ( .Values.kubeip.nodepool ) ! " .Values.kubeip.nodepool }}"
  KUBEIP_FORCEASSIGNMENT:     "{{ .Values.kubeip.forceassignment }}"
  KUBEIP_ADDITIONALNODEPOOLS: "{{ .Values.kubeip.additionalnodepools }}"
  KUBEIP_TICKER:              "{{ .Values.kubeip.ticker }}"
  KUBEIP_ALLNODEPOOLS:        "{{ .Values.kubeip.allnodepools }}"
