{{- if .Values.auth.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.auth.clusterRoleBinding.name }}
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeip.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.auth.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
