{{- if .Values.auth.create -}}
apiVersion: v1
kind: ClusterRole
metadata:
  name: {{ .Values.auth.clusterRole.name }}
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
{{- end }}
